{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-cassandra-np
  namespace: {{ .Values.namespace.name }}
  labels:
    app: cassandra
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app: cassandra
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          subdomain: {{ .Values.namespace.name }}
      podSelector:
        matchLabels:
          app: fabric
{{ end }}