apiVersion: v1
kind: Secret
metadata:
  name: cassandra-secret
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.credentials.cassandra_username }}
  password: {{ .Values.credentials.cassandra_password }}
