apiVersion: v2
appVersion: "8.3"
dependencies:
- condition: cassandra.enabled
  name: cassandra
  repository: file://../cassandra
  version: '*'
- condition: fabric.enabled
  name: fabric
  repository: file://../fabric
  version: '*'
- condition: postgres.enabled
  name: postgres
  repository: file://../postgres
  version: '*'
- condition: kafka.enabled
  name: kafka
  repository: file://../kafka
  version: '*'
- condition: neo4j.enabled
  name: neo4j
  repository: file://../neo4j
  version: '*'
- condition: DB2.enabled
  name: DB2
  repository: file://../DB2
  version: '*'
description: The following Helm Chart Deploys Fabric, Cassandra, Postgres and Kafka
name: fabric-space
type: application
version: 1.2.42
