global:
  namespace:
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

cassandra:
  enabled: true
  namespace:
    create: true
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  container:
    replicas: 1
    image:
      url: cassandra:3.11.8

      repoSecret:
        name: "registry-secret"
        enabled: false
    storage_path: "/var/lib/cassandra"
    
    resource_allocation:
      limits:
        memory: 4Gi
        cpu: '1'
      requests:
        memory: 2Gi
        cpu: '0.5'
    
    envList:
    - key: HEAP_NEWSIZE
      value: 128M
    - key: MAX_HEAP_SIZE
      value: 2G
    - key: CASSANDRA_DC
      value: DC1
    - key: CASSANDRA_ENDPOINT_SNITCH
      value: GossipingPropertyFileSnitch

  credentials:
    cassandra_username: cassandra
    cassandra_password: cassandra

  # Deploy network policy that allow ingress only from Fabric pod
  networkPolicy:
    enabled: false

  # Cassandra port
  listening_port: 9042

  storage:
    class: efs-cassandra
    alocated_amount: 10Gi

postgres:
  enabled: false
  namespace: 
    create: false
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  container:
    replicas: 1
    image:
      url: postgres:13.3

      repoSecret:
        name: "registry-secret"
        enabled: false

    storage_path: "/opt/apps/pgsql/data/data/"

    resource_allocation:
      limits:
        memory: 4Gi
        cpu: '1'

      requests:
        memory: 2Gi
        cpu: '0.4'

    envList:
    - key: PGDATA
      value: "/opt/apps/pgsql/data/data/pgdata"

  credentials:
    postgres_username: postgres
    postgres_password: postgres  

  networkPolicy:
    enabled: true
  
  # PG port
  listening_port: 5432

  storage:
    class: efs-pg
    alocated_amount: 10Gi

kafka:
  enabled: false
  namespace:
    create: false
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  container:
    replicas: 1
    image:
      url: 329508970117.dkr.ecr.eu-central-1.amazonaws.com/k2view_shared:kafka_7.2

      repoSecret:
        name: "registry-secret"
        enabled: false
        dockerRegistry:
          auths:
            "docker.share.cloud.k2view.com":
              username: ""
              password: ""
    storage_path: "/home/kafka/zk_data"

    resource_allocation:
      limits:
        memory: 4Gi
        cpu: '1'
      requests:
        memory: 2Gi
        cpu: '0.4'

    envList:
    - key: DATA
      value: "/home/kafka/zk_data"

  networkPolicy:
    enabled: true

  listening_port: 9093

  storage:
    class: efs-kafka
    alocated_amount: 10Gi  

fabric:
  enabled: true
  namespace:
    create: false
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  deploy:
    type: Deployment 
    # type = StatefulSet|Deployment

  serviceAccount:
    create: true   # For new sa, creation of sa only in k8s side
    name: ""       # For existing sa, if create is true, name should be an empty string
    provider: ""   # aws|gcp
    arn: ""        # For AWS role
    # gcp_service_account_name: "" # For GCP sa
    project_id: "" # For GCP SA
    cluster_name: ""
    azure_client_id: "" # For Azure Managed Identity
      
  container:
    replicas: 1
    resource_allocation:
      limits:
        memory: 8Gi
        cpu: '2'
      requests:
        memory: 4Gi
        cpu: '0.5'
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 60
    
    # Fabric Image to be populated into Deployment
    image:
      url: ""
      repoSecret:
        enabled: false

  storage:
    pvc:
      enabled: true
    securityContext: true
    class: efs-sc
    alocated_amount: 10Gi

  # Wether if Fabric will scale up or not
  scaling:
    enabled: false

  # Deploy network policy that allow to fabric egress only to cassandra pod
  networkPolicy:
    enabled: false

  ingress:
    enabled: true
    class_name: "nginx"
    type: "nginx"
    appgw_ssl_certificate_name: ""
    port: 3213
    host: space-tenant.domain
    tlsSecret:
      enabled: false
      key: ""
      crt: ""
      key_b64: ""
      crt_b64: ""

  custom_annotations:
    enabled: false
    annotations:
      - key: kubernetes.io/ingress.class
        value: nginx
      - key: nginx.ingress.kubernetes.io/proxy-body-size
        value: "0"
      - key: nginx.ingress.kubernetes.io/proxy-read-timeout
        value: "7d"
      - key: nginx.ingress.kubernetes.io/ssl-redirect
        value: "false"

  # Each key in the data will be mounted as a file under mountPath
  mountSecret:
    name: config-secrets
    enabled: false # true for mount the secret on fabric pod, false for mount only on init container
    mountPath: /opt/apps/fabric/config-secrets
    data:
      config: 'fabricdb|MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE|NFS\nfabricdb|MDB_DEFAULT_CACHE_PATH|/opt/apps/fabric/pod_tmp/fdb_cache\ndefault_pubsub|TYPE|MEMORY\ncommon_area_pubsub|TYPE|MEMORY\nfabric|WEB_SESSION_EXPIRATION_TIME_OUT|540\nfabric|ENABLE_BROADWAY_DEBUG_SERVLET|true\ndefault_session|RECONNECT_MAX_DELAY_MS|1000\nfabric|ENABLE_DB_INTERFACE_PROXY|true\nfabric|WEBSERVER_FILTERS|[{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/studio/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":true}},{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/socket.io/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":false}}];\nfabric|OVERRIDE_API_SCHEMA|HTTPS|ADD\nfabric|OVERRIDE_API_PORT|443|ADD\ndata_discovery|GRAPH_DB_URL|neo4j://dev-neo4j-service:7687\ndata_discovery|GRAPH_DB_USER|neo4j\ndata_discovery|GRAPH_DB_PASSWORD|changeit\n'
      cp_files: ''
      idp_cert: ''

  # Each key will be added as enviroment to the fabric container
  secretsList:
    - name: common-env-secrets
      data:
        CONFIG_UPDATE_FILE: '/opt/apps/fabric/config-secret/config'
        COPY_FILES: ''
        IDP_CERT_PATH: ''
        IDP_ROLE: ''
        INIT_CONF: ''
        PROJECT_ID: ''
        PROJECT_NAME: ''
        SPACE_NAME: ''
        ADD_CERTS: ''
    - name: cassandra-secrets
      data:
        cassandra.default.user: "cassandra"
        cassandra.default.password: "cassandra"
        cassandra.default.hosts: "cassandra-service"
  
  initSecretsList:
  - name: config-init-secrets
    data:
      IDP_CERT_PATH: ''
      IDP_ROLE: ''
      GIT_BRANCH: 'main'
      GIT_PATH_IN_REPO: ''
      GIT_REPO: ''
      GIT_TOKEN: ''
      START_FABRIC: 'false'

neo4j:
  enabled: false

  namespace:
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

  container:
    image:
      url: neo4j:5.18-enterprise
      repoSecret:
        enabled: false

    storage_path: "/var/lib/neo4j/data"

    resource_allocation:
      limits:
        memory: 4Gi
        cpu: '1'
      requests:
        memory: 2Gi
        cpu: '0.4'

    envList:
    - key: NEO4J_PLUGINS
      value: '["graph-data-science"]'
    - key: NEO4J_server_config_strict__validation_enabled
      value: "false"

  credentials:
    username: neo4j
    password: changeit

  networkPolicy:
    enabled: true

  storage:
    class: efs-pg
    alocated_amount: 10Gi
