apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.credentials.postgres_username }}
  password: {{ .Values.credentials.postgres_password }}
