{{- if .Values.container.image.repoSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.image.repoSecret.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.container.image.repoSecret.dockerRegistry | toJson | b64enc }}
{{- end }}
