{{- range .Values.secretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- range .Values.initSecretsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
type: Opaque
data:
{{- range $key, $value := .data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}