{{- if and .Values.ingress.tlsSecret.enabled (or (and (ne .Values.ingress.tlsSecret.key "") (ne .Values.ingress.tlsSecret.crt "")) (and (ne .Values.ingress.tlsSecret.key_b64 "") (ne .Values.ingress.tlsSecret.crt_b64 ""))) }}
apiVersion: v1
kind: Secret
metadata:
  name: fabric-private-ingress-ssl
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/tls
stringData:
  {{- if .Values.ingress.tlsSecret.key_b64 }}
  tls.key: {{ .Values.ingress.tlsSecret.key_b64 | quote }}
  tls.crt: {{ .Values.ingress.tlsSecret.crt_b64 | quote }}
  {{- else if .Values.ingress.tlsSecret.key }}
  tls.key: {{ .Values.ingress.tlsSecret.key | b64enc | quote }}
  tls.crt: {{ .Values.ingress.tlsSecret.crt | b64enc | quote }}
  {{- end }}
{{- end }}