{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-fabric-np
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fabric
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app: fabric
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: cassandra
    ports:
    - port: 9042
    - port: 9142
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - port: 5432
  - to:
    ports:
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
{{ end }}