{{ if .Values.scaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: fabric-hpa
    namespace: {{ .Values.namespace.name }}
    labels:
        app: fabric
        {{- range $label := .Values.labels }}
        {{ $label.name }}: {{ $label.value }}
        {{- end }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: {{ .Values.scaling.targetKind }}
        name: {{ .Values.scaling.targetName }}
    minReplicas: {{ .Values.scaling.minReplicas }}
    maxReplicas: {{ .Values.scaling.maxReplicas }}
    targetCPUUtilizationPercentage: {{ .Values.scaling.targetCPU }}
{{ end }}