{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fabric-ingresss
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fabric
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  annotations:
    {{- if and .Values.ingress.custom_annotations.enabled }}
    {{- range $label := .Values.ingress.custom_annotations.annotations }}
    {{ $label.key }}: {{ $label.value | quote }}
    {{- end }}
    {{- else if eq .Values.ingress.type "nginx" }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7d"
    {{- else if eq .Values.ingress.type "appgw" }}
    {{- if ne .Values.ingress.appgw_ssl_certificate_name "" }}
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.ingress.appgw_ssl_certificate_name }}
    {{- end }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if and .Values.ingress.cert_manager.enabled (ne .Values.ingress.cert_manager.cluster_issuer "") }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.cert_manager.cluster_issuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class_name }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    {{- if and .Values.ingress.tlsSecret.enabled (ne .Values.ingress.tlsSecret.key "") (ne .Values.ingress.tlsSecret.crt "") }}
    secretName: fabric-private-ingress-ssl
    {{- else if .Values.ingress.cert_manager.enabled }}
    secretName: cert-manager-ssl-cert
    {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /{{- if .Values.ingress.path }}{{ .Values.ingress.path }} {{- end }}
          pathType: Prefix
          backend:
            service:
              name: fabric-service
              port:
                number: {{ .Values.ingress.port }}
{{ end }}
