{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fabric-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fabric
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    {{- if and .Values.ingress.tlsSecret.enabled (or (and (ne .Values.ingress.tlsSecret.key "") (ne .Values.ingress.tlsSecret.crt "")) (and (ne .Values.ingress.tlsSecret.key_b64 "") (ne .Values.ingress.tlsSecret.crt_b64 ""))) }}
    secretName: fabric-private-ingress-ssl
    {{- else if .Values.ingress.cert_manager.enabled }}
    secretName: cert-manager-ssl-cert
    {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /{{- if .Values.ingress.path }}{{ .Values.ingress.path }} {{- end }}
          pathType: Prefix
          backend:
            service:
              name: fabric-service
              port:
                number: {{ .Values.ingress.port }}
{{ end }}
