apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mountSecret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
{{- range $key, $value := .Values.mountSecret.data }}
{{- if $value }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}