{{ if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace.name }}-sa
  namespace: {{ .Values.namespace.name }}
  {{ if eq .Values.serviceAccount.provider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.arn }}"
  {{ else if eq .Values.serviceAccount.provider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccount.cluster_name }}-space-sa@{{ .Values.serviceAccount.project_id }}.iam.gserviceaccount.com"
  {{ else if eq .Values.serviceAccount.provider "azure" }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.serviceAccount.azure_client_id }}"
  labels:
    azure.workload.identity/use: "true"
  {{ end }}

{{ end }}
