apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: neo4j
type: Opaque
data:
  neo4j_auth: {{ printf "%s/%s" .Values.credentials.username .Values.credentials.password | b64enc }}
