apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
  namespace: {{ .Values.namespace.name }}
  labels: &id001
    app: neo4j
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels: *id001
    spec:
      {{- if .Values.container.image.repoSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.container.image.repoSecret.name }}
      {{- end }}
      {{- if or (eq .Values.affinity.type "affinity") (eq .Values.affinity.type "anti-affinity") }}
      affinity:
        {{- if eq .Values.affinity.type "affinity" }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.label.name }}
                operator: In
                values:
                - {{ .Values.affinity.label.value }}
        {{- else if eq .Values.affinity.type "anti-affinity" }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.label.name }}
                operator: NotIn
                values:
                - {{ .Values.affinity.label.value }}
        {{- end }}
      {{- end }}
      containers:
      - name: neo4j
        image: {{ .Values.container.image.url }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 7867
        resources:
          limits:
            memory: {{ .Values.container.resource_allocation.limits.memory }}
            cpu: {{ .Values.container.resource_allocation.limits.cpu }}
          requests:
            memory: {{ .Values.container.resource_allocation.requests.memory }}
            cpu: {{ .Values.container.resource_allocation.requests.cpu }}
        env:
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-secret
              key: neo4j_auth
        {{- range $env := .Values.container.envList }}
        - name: {{ $env.key }}
          value: {{ $env.value | squote }}
        {{- end }}
        volumeMounts:
          - name: neo4j-storage
            mountPath: {{ .Values.container.storage_path }}
      volumes:
      - name: neo4j-storage
        persistentVolumeClaim:
          claimName: neo4j-claim
