global:
  namespace:
    create: false
    name: "space-tenant"

  labels:
    - name: tenant
      value: my-tenant
    - name: space
      value: my-space

namespace:
  create: false
  name: "space-tenant"

labels:
  - name: tenant
    value: my-tenant
  - name: space
    value: my-space

container:
  replicas: 1
  image:
    url: cassandra:3.11.8

    repoSecret:
      name: "registry-secret"
      enabled: false
      dockerRegistry:
        auths:
          "docker.share.cloud.k2view.com":
            username: ""
            password: ""
  storage_path: "/var/lib/cassandra"
  
  resource_allocation:
    limits:
      memory: 4Gi
      cpu: '1'
    
    requests:
      memory: 2Gi
      cpu: '0.4'
  
  envList:
  - key: HEAP_NEWSIZE
    value: 128M
  - key: MAX_HEAP_SIZE
    value: 2G
  - key: CASSANDRA_DC
    value: DC1
  - key: CASSANDRA_ENDPOINT_SNITCH
    value: GossipingPropertyFileSnitch

credentials:
  cassandra_username: cassandra
  cassandra_password: cassandra

networkPolicy:
  enabled: true

# Cassandra port
listening_port: 9042

storage:
  class: gp2
  alocated_amount: 10Gi

affinity:
  type: none  # Options: affinity, anti-affinity, none
  label: 
    name: topology.kubernetes.io/zone
    value: region-a

