{{ $namespace := default dict .Values.namespace }}
{{ $serviceAccount := default dict .Values.serviceAccount }}

{{ if $serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Release.Name $namespace.name }}-sa
  namespace: {{ default .Release.Name $namespace.name }}
  {{- if eq $serviceAccount.provider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ $serviceAccount.arn }}"
  {{ else if eq $serviceAccount.provider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $serviceAccount.cluster_name }}-space-sa@{{ $serviceAccount.project_id }}.iam.gserviceaccount.com"
  {{ else if eq $serviceAccount.provider "azure" }}
  annotations:
    azure.workload.identity/client-id: "{{ $serviceAccount.azure_client_id }}"
  {{ end }}
{{ end }}
