apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace.name }}
  name: db2-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: db2
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 50000
