global:
  labels:
    #- name: label-name
    #  value: label-value

namespace:
  create: false
  name: "space-tenant"

deploy:
  type: Deployment # Deployment|StatefulSet

serviceAccount:
  create: true   # For new sa, creation of sa only in k8s side
  name: ""       # For existing sa, if create is true, name should be an empty string
  provider: ""   # aws|gcp
  arn: ""        # For AWS role
  # gcp_service_account_name: "" # For GCP sa
  project_id: "" # For GCP SA
  cluster_name: ""
  azure_client_id: "" # For Azure Managed Identity

container:
  replicas: 1
  annotationsList:
  - name: description
    value: Fabric on Kubernetes
  resource_allocation:
    limits:
      memory: 8Gi
      cpu: '2'
    requests:
      memory: 2Gi
      cpu: '0.4'

  # Fabric Image to be populated into Deployment
  image:
    url: "" 
    repoSecret:
      name: "registry-secret"
      enabled: false
      dockerRegistry:
        auths:
          "docker.share.cloud.k2view.com":
            username: ""
            password: ""

storage:
  pvc:
    enabled: true
  securityContext: true
  class: managed
  alocated_amount: 10Gi

# Wether if Fabric will scale up or not
scaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 90

# Deploy network policy that allow to fabric egress only to cassandra pod
networkPolicy:
  egress:
    enabled: false
# Ingress Network Policy
  ingress:
    enabled: false
    allowedNamespaces:
      name: grafana-agent
    allowedPods: 
      app.kubernetes.io/instance: grafana-agent
    allowedIPs:
      # - 10.0.0.1/16

ingress:
  enabled: true
  class_name: "nginx"
  type: "nginx"
  appgw_ssl_certificate_name: ""
  cert_manager:
    enabled: false
    cluster_issuer: ""
  host: space-tenant.domain
  tlsSecret:
    enabled: false

  custom_annotations:
    enabled: false
    annotations:
      - key: nginx.ingress.kubernetes.io/proxy-body-size
        value: "0"
      - key: nginx.ingress.kubernetes.io/proxy-read-timeout
        value: "86400"
      - key: nginx.ingress.kubernetes.io/proxy-send-timeout
        value: "900"
      - key: nginx.ingress.kubernetes.io/ssl-redirect
        value: "false"

# Mounting secrets to the fabric pod will be decoded to base64
mountSecret:
    name: config-secrets
    enabled: false # true for mount the secret on fabric pod, false for mount only on init container
    mountPath: /opt/apps/fabric/config-secrets
    data:
      config: |
        fabricdb|MDB_DEFAULT_CACHE_PATH|/opt/apps/fabric/pod_tmp/fdb_cache
        default_pubsub|TYPE|MEMORY
        common_area_pubsub|TYPE|MEMORY
        fabric|WEB_SESSION_EXPIRATION_TIME_OUT|540
        fabric|ENABLE_BROADWAY_DEBUG_SERVLET|true
        default_session|RECONNECT_MAX_DELAY_MS|1000
        fabric|ENABLE_DB_INTERFACE_PROXY|true
        fabric|WEBSERVER_FILTERS|[{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/studio/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":true}},{\"class\":\"com.k2view.cdbms.ws.ProxyForward\",\"patterns\":[\"/socket.io/*\"],\"params\":{\"target\":\"http://localhost:3000\",\"isStaticTarget\":false}}];
        fabric|OVERRIDE_API_SCHEMA|HTTPS|ADD
        fabric|OVERRIDE_API_PORT|443|ADD
        system_db|SYSTEM_DB_TYPE|SQLITE
        system_db|SYSTEM_DB_HOST|/opt/apps/fabric/workspace/internal_db
        fabric|SERVER_AUTHENTICATOR|fabric
      cp_files: ''
      idp_cert: ''

# Mounting secrets to the fabric pod will be not decoded to base64
mountSecretB64enc:
    name: mount-b64-secrets
    enabled: false # true for mount the secret on fabric pod, false for mount only on init container
    mountPath: /opt/apps/fabric/config-secrets
    data:
      placeholder: ''

secretsList:
  - name: common-env-secrets
    data:
      PROJECT_ID: ''
      PROJECT_NAME: ''
      SPACE_NAME: ''

initSecretsList:
  - name: config-init-secrets
    data:
      CONFIG_UPDATE_FILE: '/opt/apps/fabric/config-secrets/config'
      COPY_FILES: '/opt/apps/fabric/config-secrets/cp_files'
      IDP_CERT_PATH: ''
      IDP_ROLE: ''
      GIT_BRANCH: ''
      GIT_PATH_IN_REPO: ''
      GIT_REPO: ''
      GIT_TOKEN: ''
      START_FABRIC: 'false' 

affinity:
  type: none  # Options: affinity, anti-affinity, none
  label: 
    name: topology.kubernetes.io/zone
    value: region-a
